import "./index.html";
import "./index.scss";
import "./scripts/deleteBook.ts";
import "./scripts/details.ts";
import "./scripts/signout.ts";
import "./scripts/books.ts";
import "./scripts/signin.ts";
import "./scripts/signup.ts";
import "./scripts/addBook.ts";
